variables:
  POSTGRES_USER: disco_pguser
  POSTGRES_PASSWORD: disco_pgpassword
  POSTGRES_DB: disco_app

image: ruby:2.3
services:
  - postgres:9.4

before_script:
  # Install dependencies
  - apt-get update -qy
  - apt-get install -y nodejs
  # Set up Ruby and gems
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle config build.nokogiri --use-system-libraries
  - bundle install
  # Set Rails environment
  - export RAILS_ENV=test
  # Copy the GitLab database configuration
  - cp "test/dummy/config/database.gitlab-ci.yml" "test/dummy/config/database.yml"
  # Load database schema
  - bundle exec rake db:schema:load

runtests:
  script:
    - bundle exec rake test
